version: "3"
services:
  server:
    build:
      context: ../
      dockerfile: ./scripts/Dockerfile
    container_name: ${SERVER_NAME}
    volumes:
      - ../:/usr/server/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
#    depends_on:
#      - database
#  database:
#    image: "postgres:latest"
#    container_name: ${DB_NAME}
#    ports:
#      - ${DB_PORT}:${DB_PORT}
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      PGPASSWORD: ${DB_PASSWORD}

